#!/bin/ksh -p
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, and/or sell copies of the Software, and to permit persons
# to whom the Software is furnished to do so, provided that the above
# copyright notice(s) and this permission notice appear in all copies of
# the Software and that both the above copyright notice(s) and this
# permission notice appear in supporting documentation.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
# OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL
# INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Except as contained in this notice, the name of a copyright holder
# shall not be used in advertising or otherwise to promote the sale, use
# or other dealings in this Software without prior written authorization
# of the copyright holder.
#
###########################################################################
#

PATH=/usr/bin:/usr/sbin

. /lib/svc/share/smf_include.sh

USAGE="Usage: $0 <method>"

if [ $# -ne 1 ] ; then
    echo $USAGE
    exit 2
fi

METHOD=$1

case $METHOD in
    start)
	# Continue with rest of script
	;;
    -*)
	echo $USAGE
	exit 2
	;;
    *)
	echo "Invalid method $METHOD"
	exit 2
	;;
esac


#
# IF the gconf cache exist then :
#   find schema files newer than the cache 
# ELSE
#   get all schema file
#
# generate/merge schema files in the gconf cache
#

IFS=" 
"
if [ -a "/etc/gconf/gconf.xml.defaults/%gconf-tree.xml" ]; then
  SCHEMAS=`/usr/bin/find /etc/gconf/schemas ! -type d -follow \
    -name '*.schemas' \
    -newer /etc/gconf/gconf.xml.defaults/%gconf-tree.xml 2>/dev/null`
  ENTRIES=`/usr/bin/find /etc/gconf/schemas ! -type d -follow \
    -name '*.entries' \
    -newer /etc/gconf/gconf.xml.defaults/%gconf-tree.xml 2>/dev/null`
else
  SCHEMAS=`/usr/bin/find /etc/gconf/schemas -name '*.schemas' ! -type d`
  ENTRIES=`/usr/bin/find /etc/gconf/schemas -name '*.entries' ! -type d`
fi

if [ -n "$SCHEMAS" ]; then 
  echo "Updating GConf cache for the following schemas:"
  echo "$SCHEMAS" | /bin/sed -e 's/^/    /'
  # redirect stdout to /dev/null because gconftool is too verbose
  # errors are printed to stderr
  GCONF_CONFIG_SOURCE=xml:merged:/etc/gconf/gconf.xml.defaults \
    /usr/bin/gconftool-2 --makefile-install-rule $SCHEMAS > /dev/null
  if [ $? -ne 0 ]; then
    echo "gconftool-2 exited with an error while installing schemas"
    exit $SMF_EXIT_ERR_FATAL
  else
    echo "Schema files merged in the GConf cache"
  fi
fi

if [ -n "$ENTRIES" ]; then 
  echo "Updating GConf cache for the following entries:"
  echo "$ENTRIES" | /bin/sed -e 's/^/    /'
  # redirect stdout to /dev/null because gconftool is too verbose
  # errors are printed to stderr
  /usr/bin/gconftool-2 --direct \
      --config-source=xml:merged:/etc/gconf/gconf.xml.defaults \
      --load $ENTRIES > /dev/null
  if [ $? -ne 0 ]; then
    echo "gconftool-2 exited with an error while adding entries"
    exit $SMF_EXIT_ERR_FATAL
  else
    echo "Entries merged into the GConf cache"
  fi
fi
